# Generated by Django 5.0.3 on 2024-04-01 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_stu_add_student_add_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Add',
            field=models.CharField(max_length=100, verbose_name='Student_address'),
        ),
        migrations.AlterField(
            model_name='student',
            name='Contact',
            field=models.IntegerField(verbose_name='Student_contact'),
        ),
        migrations.AlterField(
            model_name='student',
            name='Email',
            field=models.EmailField(max_length=254, verbose_name='Student_email'),
        ),
        migrations.AlterField(
            model_name='student',
            name='Name',
            field=models.CharField(max_length=50, verbose_name='Student_name'),
        ),
    ]
