# Generated by Django 5.0.3 on 2024-04-01 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_student_add_alter_student_contact_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'get_latest_by': 'order_date', 'ordering': [-1], 'verbose_name': 'stu'},
        ),
        migrations.AlterModelTableComment(
            name='student',
            table_comment='Question answers',
        ),
        migrations.AlterModelTable(
            name='student',
            table='stu_table',
        ),
    ]
