# Generated by Django 5.0.3 on 2024-04-01 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_student_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table=None,
        ),
    ]
