# Generated by Django 5.0.3 on 2024-04-01 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_student_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['Name'], 'verbose_name': 'stu', 'verbose_name_plural': 'Student'},
        ),
        migrations.AlterModelTableComment(
            name='student',
            table_comment=None,
        ),
    ]
