# Generated by Django 5.0.3 on 2024-04-02 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_student_country'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['Name'], 'verbose_name_plural': 'Student'},
        ),
        migrations.AlterField(
            model_name='student',
            name='Country',
            field=models.CharField(choices=[('ind', 'india'), ('CA', 'Canada'), ('MX', 'Mexico'), ('1', 'One'), ('2', 'Two'), ('3', 'Three'), ('4', 'Four'), ('5', 'Five')], max_length=100, null=True),
        ),
    ]
