# Generated by Django 5.0.3 on 2024-04-02 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_student_options_alter_student_country'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={},
        ),
        migrations.AlterModelTable(
            name='student',
            table=None,
        ),
    ]
