# Generated by Django 5.0.3 on 2024-04-02 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_student_options_alter_student_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['Name']},
        ),
    ]
